# -*- coding: utf-8 -*-
"""Linear_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ydS6jsZthpu0OVRO5bBwhJp3gWrOiYua
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

medical_charges_url = 'https://raw.githubusercontent.com/JovianML/opendatasets/master/data/medical-charges.csv'

from urllib.request import urlretrieve

urlretrieve(medical_charges_url, "medical.cv")

medical_data = pd.read_csv("medical.cv")

medical_data

smoker_data = medical_data[medical_data['smoker'] == 'yes']

non_smoker_data = medical_data[medical_data['smoker'] == 'no']

plt.scatter(smoker_data['age'], smoker_data['charges'], alpha =0.7, s =20)

plt.show()

def model_example(ages, w, b):
  return w * ages + b

def root_mean_square_error(predictions, targets):
  return np.sqrt(np.mean(np.square(predictions-targets)))

ages = smoker_data['age']
w = 290
b = 22000

values = model_example(ages, w, b)

plt.scatter(ages, smoker_data['charges'])
plt.scatter(ages, values)

plt.show()

root_mean_square_error(values, smoker_data['charges'])

from sklearn.linear_model import LinearRegression

#Ordinary Least Squares Method

inputs = smoker_data[['age']]
targets = smoker_data['charges']


model = LinearRegression()

model.fit(inputs, targets)

predictions = model.predict(inputs)

loss = root_mean_square_error(predictions, targets)
print("Rmse: ", loss)

plt.scatter(inputs, targets)
plt.scatter(inputs, predictions)
plt.show()

from sklearn.linear_model import LinearRegression

#Ordinary Least Squares Method

inputs = non_smoker_data[['age']]
targets = non_smoker_data['charges']

model = LinearRegression()

model.fit(inputs, targets)

prediction = model.predict(inputs)
#prediction= model.predict(np.array([[18],[34],[56],[78],[23],[18],[22],[32],[45]]))

loss = root_mean_square_error(prediction, targets)
print("RMSE: ", loss)
print("w: ", model.coef_)
print("b: ", model.intercept_)
print(prediction)

plt.scatter(inputs, targets, alpha = 0.7, s=15)
plt.scatter(inputs, prediction)

plt.show()

!pip install scikit-learn

#Now Let us use Stochastic Gradient Descendent Method.

#Here i am using same data to train and test.

import numpy as np
from sklearn.linear_model import SGDRegressor
from sklearn.preprocessing import StandardScaler

inputs = non_smoker_data[['age']]
targets = non_smoker_data['charges']

Scaler = StandardScaler()

inputs = Scaler.fit_transform(inputs)

model = SGDRegressor(max_iter = 1000, learning_rate="invscaling")

model.fit(inputs, targets)

prediction = model.predict(inputs)

loss = np.sqrt(np.mean(np.square(targets-prediction)))
print("Rmse: ", loss)

plt.scatter(inputs, targets)
plt.scatter(inputs, prediction)

plt.show()

#We will perform SGD Regression process
# Here, i will split the training and testing data seperately(80% train, 20% test) from the same dataset


from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import SGDRegressor
from sklearn.model_selection import train_test_split

x = non_smoker_data[['age']]
y = non_smoker_data['charges']

#Splitting Data
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)


#Scalling Data

Scaler = StandardScaler()

x_scalar_train = Scaler.fit_transform(x_train)
x_scalar_test = Scaler.transform(x_test)

#Now Applying the model

model = SGDRegressor(max_iter = 1500, learning_rate='invscaling', random_state = 42)

model.fit(x_scalar_train, y_train)

prediction = model.predict(x_scalar_test)

loss = np.sqrt(np.mean(np.square(y_test-prediction)))
print("RMSE:  ", loss)
print("w: ", model.coef_)
print("b: ", model.intercept_)

plt.scatter(x_train,y_train)
plt.scatter(x_test, prediction)

plt.show()

#Now, i will include all the weights in Ordinary Least Squares method

#For that i need to convert the string(non-integer values and classify the other weights)

# In our dataset, we need to classify smoker and region

#Classifying Smoker
smoker_codes = {"yes": 1, "no": 0}
medical_data['smoker_codes'] = medical_data.smoker.map(smoker_codes)



#Classifying Region
#We need to use "onehotencoder" to encode the region of 4 values.

from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output = False)
region_encoder = encoder.fit_transform(medical_data[['region']]).astype(int)

#Now i am appending or concatinating this to my medical_data csv file

medical_data[['northeast', 'northwest', 'southeast', 'southwest']] = region_encoder



#Now Let's change for sex too

sex_codes = {'female': 0, 'male':1}
medical_data['sex_codes'] = medical_data.sex.map(sex_codes)

medical_data

#Now Lets add all the weights and lets implement the LinearRegression model for non_smoker_model


from sklearn.linear_model import LinearRegression

# Filter non-smoker data using the numerical 'smoker_codes' column
non_smoker_data = medical_data[medical_data['smoker_codes'] == 0]

# Correctly select multiple columns as input features by passing a single list of column names
inputs = non_smoker_data[['age', 'sex_codes', 'bmi', 'children', 'northeast', 'northwest','southeast','southwest']]
targets = non_smoker_data['charges']

model = LinearRegression()

model.fit(inputs, targets)

predictions = model.predict(inputs)

loss = root_mean_square_error(predictions, targets)
print("RMSE: ", loss)
print("W: ", model.coef_)
print("b: ", model.intercept_)

# Plotting with 'age' as the x-axis for better visualization
plt.scatter(non_smoker_data['age'], targets, label='Actual', alpha=0.7, s =20)
plt.scatter(non_smoker_data['age'], predictions, label='Predicted', alpha = 0.7, s = 20)

plt.legend()
plt.xlabel("Age") # Changed label to 'Age' since we are plotting age
plt.ylabel("Charges")
plt.title("Linear_Regression_Model")

plt.show()

#Now lets do for the smoker_data

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split


smoker_data = medical_data[medical_data['smoker_codes'] == 1]

inputs = smoker_data[['age', 'bmi', 'sex_codes', 'children', 'northeast', 'northwest','southeast', 'southwest', ]]
targets = smoker_data['charges']

#splitting the data

x_train, x_test, y_train, y_test = train_test_split(inputs, targets ,test_size = 0.2, random_state=42)

model = LinearRegression()

model.fit(x_train, y_train)

prediction = model.predict(x_test)

loss = root_mean_square_error(prediction, y_test)
print("RMSE: ", loss)
print("w: ", model.coef_)
print("b: ", model.intercept_)

# Plotting 'age' from x_test against y_test and prediction
plt.scatter(x_test['age'], y_test, label='Actual')
plt.scatter(x_test['age'], prediction, label='Predicted')
plt.legend(['Actual', 'Prediction'])
plt.xlabel('Age')
plt.ylabel('Charges')
plt.title('Smoker Data: Linear Regression Model')

plt.show()